apiVersion: apps/v1
kind: Deployment
metadata:
  name: proposal
  namespace: ezinsurance
  labels:
    app: proposal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proposal
  template:
    metadata:
      labels:
        app: proposal
    spec:
      containers:
        - name: proposal
          image: ycyang73/ezinsurance-proposal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
            - name: api.url.payment
              valueFrom:
                configMapKeyRef:
                  name: ezinsurance-config
                  key: api.url.payment
            - name: DATASOURCE_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: ezinsurance-config
                  key: datasource.schema
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: ezinsurance-config
                  key: datasource.username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ezinsurance-config
                  key: datasource.password
#환경설정 END
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: proposal
  namespace: ezinsurance
  labels:
    app: proposal
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: proposal
